### ISSUE TITLE
event: Wikipedia censors name of alleged Ukraine whistleblower

### ISSUE THREAD

**Issue by steverusso** [steverusso/bigtech.fail#14]
* 9 Nov 2019
* Wikipedia admins completely remove and ban any content containing the name Eric Ciaramella
* [Primary (only?) news source](https://www.breitbart.com/tech/2019/11/10/wikipedia-admins-censor-name-of-alleged-ukraine-whistleblower/)
* [Ex 1: Wumbolo ArbCom request](https://en.wikipedia.org/w/index.php?title=Wikipedia:Arbitration/Requests/Case&diff=925399016&oldid=925398271) (& [archived](https://archive.vn/br8fC))
* [Ex 2: Reddit thread on the matter](https://www.reddit.com/r/WikiInAction/comments/du2nnn/wikipedia_wont_allow_anyone_to_talk_about_eric/) (& [archived](https://archive.is/7vUZW))
* [Great resource](https://heavy.com/news/2019/10/eric-ciaramella/) on Eric Ciaramella, including a thorough timeline of when his name was publicized and by whom

**Comment by steverusso** [comment]
https://github.com/steverusso/bigtech.fail/commit/613216a10a5cd823966ad54298f4780671dd2ae5

**Comment by ValZapod** [comment]
Youtube still removes the name in comments.

**Comment by steverusso** [comment]
Ah, I should mention that somewhere, maybe in one of the events.

Thanks for the comment!
